version: "3"
services:
  app:
    build: .
    command: npx knex migrate:latest && npm start
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bona123
      POSTGRES_DB: bona_filmes